solana-indexer:
  image:
    repository: solana-indexer-solana-indexer
  blockchain: solana
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.env" $ }}/protocol/{{ .Values.blockchain }}/nft'
    SPRING_PROFILES_ACTIVE: '{{ .Values.blockchain }},consul,{{ include "service.env" $ }},{{ .Values.blockchain }}-{{ include "service.env" $ }}'
    JAVA_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000'
  nodeSelector:
    node.labels.rarible.job: true
  updateConfig:
    order: stop-first
  resources:
    jvm:
      xmx_megabytes: 6096
      max_direct_memory_megabytes: 1524
  livenessProbe:
    initialDelaySeconds: 180
  podAnnotations:
    fluentbit.io/parser: logfmt

solana-api:
  image:
    repository: solana-indexer-solana-api
  blockchain: solana
  service:
    enabled: true
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.env" $ }}/protocol/{{ .Values.blockchain }}/nft'
    SPRING_PROFILES_ACTIVE: '{{ .Values.blockchain }},consul,{{ include "service.env" $ }},{{ .Values.blockchain }}-{{ include "service.env" $ }}'
  nodeSelector:
    node.labels.rarible.job: true
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 32
  livenessProbe:
    initialDelaySeconds: 180
  podAnnotations:
    fluentbit.io/parser: logfmt

solana-migration:
  image:
    repository: solana-indexer-solana-migration
  blockchain: solana
  service:
    enabled: true
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.env" $ }}/protocol/{{ .Values.blockchain }}/nft'
    SPRING_PROFILES_ACTIVE: '{{ .Values.blockchain }},consul,{{ include "service.env" $ }},{{ .Values.blockchain }}-{{ include "service.env" $ }}'
  nodeSelector:
    node.labels.rarible.job: true
  restartPolicy:
    condition: on-failure
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 32
  livenessProbe:
    initialDelaySeconds: 180
  podAnnotations:
    fluentbit.io/parser: logfmt
