spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.hosts}
      database: ${mongodb.database}

redisUri: ${redis.uri}

blockchain:
  scanner:
    kafka:
      broker-replica-set: ${kafka.hosts}

common:
  metricRootPath: solana-nft-metrics
  kafka-replica-set: ${kafka.hosts}
