application:
  project: protocol

server:
  shutdown: graceful
  port: 8080

spring:
  application:
    name: protocol-solana-nft-indexer
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  codec:
    max-in-memory-size: 50MB
  aop:
    proxy-target-class: false
  main:
    banner-mode: log
    web-application-type: reactive

mongock:
  change-logs-scan-package:
    - com.rarible.protocol.solana.nft.listener.migration

common:
  metricRootPath: solana-nft-metrics

rarible:
  core:
    apm:
      agent:
        enabled: true
        server: http://elk_apm-server:8200
        packages: com.rarible.protocol.solana.nft.listener
      web:
        filter:
          enabled: true
      annotation:
        enabled: true

blockchain:
  scanner:
    kafka:
      numberOfPartitionsPerLogGroup: 100
    solana:
      service: protocol-solana-nft-listener
      rpcApiUrls: https://still-holy-lake.solana-testnet.quiknode.pro/37d77e8a7fd97d3f9f19da391bfe285aceaef7b5/
      scan:
        batchLoad:
          batchSize: 100
          enabled: true
      retryPolicy:
        scan:
          reconnectDelay: 2s
          reconnectAttempts: 10
        client:
          delay: 2s
          attempts: 3
      job:
        reconciliation:
          enabled: false
          batchSize: 5
      monitoring:
        enabled: true
        rootPath: "blockchain.scanner"
        worker:
          pollingPeriod: 1m
